//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WineShopManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string Email { get; set; }
        public Nullable<int> RateListID { get; set; }
        public Nullable<int> WineID { get; set; }
    
        public virtual RateList RateList { get; set; }
        public virtual Wine Wine { get; set; }
    }
}
